# site and author details
title: 'TESLABS'
description: >
    TESLABS is the personal web page of Gerard Marull-Paretas, where you will
    find his profile and some technical articles

author:
    name: 'Gerard Marull-Paretas'
    email: 'gerardmarull@gmail.com'
    url: 'https://www.teslabs.com'

# setup
plugins: [jekyll-paginate]

permalink: '/articles/:title/'

paginate: 5
paginate_path: 'articles/page/:num'

# pages
navigation:
- text: Home
  url: /
- text: Articles
  url: /articles/
- text: Me
  url: /cv/
