# site and author details
title: 'Teslabs Engineering'
description: >
    Teslabs Engineering is a company offering a wide range of engineering
    services.

url: 'https://teslabs.com'

author:
    name: 'Gerard Marull-Paretas'
    email: 'gerard@teslabs.com'
    url: 'https://www.teslabs.com'

# setup
plugins: [jekyll-paginate]

permalink: '/articles/:title/'

paginate: 5
paginate_path: 'articles/page/:num'

# pages
navigation:
- text: Home
  url: /
- text: Services
  url: /services/
- text: Portfolio
  url: /portfolio/
- text: Articles
  url: /articles/
- text: Contact
  url: /contact/
